### ISSUE TITLE
deploying docs from travis fails

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-unsynced-local-docs#7]
```
$ npm run deploydocs
Error: Failed to replace env in config: ${NPM_API_KEY}
    at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npmconf/npmconf.js:423:13
        at String.replace (native)
        at envReplace (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npmconf/npmconf.js:418:12)
        at parseField (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npmconf/npmconf.js:397:7)
        at /home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npmconf/npmconf.js:339:15
        at Array.forEach (native)
        at Conf.add (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npmconf/npmconf.js:338:21)
        at ConfigChain.addString (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain/index.js:244:8)
        at Conf.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/node_modules/npmconf/npmconf.js:327:10)
        at fs.js:272:14
        /home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/npm.js:32
    throw new Error('npm.load() required')
              ^
              Error: npm.load() required
    at Object.npm.config.get (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/npm.js:32:11)
        at exit (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/utils/error-handler.js:51:40)
        at process.errorHandler (/home/travis/.nvm/v0.10.36/lib/node_modules/npm/lib/utils/error-handler.js:342:3)
        at process.emit (events.js:95:17)
        at process._fatalException (node.js:295:26)
after_script
```

**Comment by zoepage** [comment]
will look into it with @boennemann tomorrow.

**Comment by boennemann** [comment]
This should be fixed with #9.
As of lately Travis seems to cleanup sensitive variables from the env after the deploy step. They did forget to cleanup the .npmrc file though, hence npm fails to load its config.

**Comment by gr2m** [comment]
@boennemann I don't fully understand what we need to do to fix it to be honest :) Also, you referenced this issue in your comment, I think you meant to reference some other thing?

**Comment by gr2m** [comment]
@boennemann looks like thisll failing? https://travis-ci.org/hoodiehq/pouchdb-hoodie-unsynced-local-docs/jobs/70788603#L224

**Comment by boennemann** [comment]
@gr2m I'm pretty sure that that's the rough idea of how to fix it – hard to test. Probably we just need to add an `export` in front.

semantic-release@next will be there very soon, so I don't want to lose too much time playing computers with Travis, when it's fixed with the new version anyway.

**Comment by gr2m** [comment]
aye, makes sense. Let's just keep the issue open and get back once `semantic-release@next` is out
